name: scholarships
description: Application with best and every scholarship in Poland
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  injectable: ^2.5.0
  get_it: ^8.0.3
  
  either_dart: ^1.0.0

  go_router: ^16.0.0
  url_launcher: ^6.3.1
  
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  top_snackbar_flutter: ^3.3.0

  cloud_firestore: ^5.6.11
  firebase_core: ^3.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
  - .env
  - assets/img/3047937.png
